import type { LibraryDomain, LibraryTerm } from "@/lib/prospection-demo";

export type HelpLibraryItem = {
  line: LibraryDomain;
  category: string;
  title: string;
  body: string;
  terms?: LibraryTerm[];
};

const lex = (
  line: LibraryDomain,
  title: string,
  body: string,
  terms: LibraryTerm[],
): HelpLibraryItem => ({ line, category: "Lexique", title, body, terms });

export const HELP_LIBRARY: HelpLibraryItem[] = [
  lex(
    "comptabilite",
    "Tenue, révision et états financiers",
    "Vocabulaire à utiliser avec un DAF ou un chef comptable. On parle de fiabilité des comptes, pas de « mise en ordre des papiers ».",
    [
      { term: "SYSCOHADA révisé", def: "Plan comptable OHADA en vigueur : cadres, comptes et états financiers de référence." },
      { term: "Journal", def: "Enregistrement chronologique des pièces : achats, ventes, banque, opérations diverses." },
      { term: "Grand livre", def: "Reprise de chaque compte, écriture par écriture, pour justifier un solde." },
      { term: "Balance", def: "Liste des comptes avec totaux débit, crédit et solde. Point de départ de la révision." },
      { term: "Bilan", def: "Photo du patrimoine à la clôture : actif, passif et capitaux propres." },
      { term: "Compte de résultat", def: "Produits moins charges de l’exercice : le résultat net." },
      { term: "Notes annexes", def: "Explications obligatoires : méthodes, immobilisations, dettes, engagements." },
      { term: "TAFIRE", def: "Tableau financier des ressources et des emplois : d’où vient la trésorerie et où elle va." },
      { term: "Rapprochement bancaire", def: "Écart expliqué entre le relevé banque et le compte 52." },
      { term: "Cut-off", def: "Rattachement des charges et produits au bon exercice, ni avant ni après." },
      { term: "Immobilisation", def: "Bien durable inscrit à l’actif et amorti selon un plan." },
      { term: "Liasse fiscale", def: "Jeu d’états transmis à l’administration avec la déclaration de résultat." },
    ],
  ),
  {
    line: "comptabilite",
    category: "Cibles prioritaires",
    title: "Qui décide sur la comptabilité",
    body: "DAF, chef comptable, expert-comptable interne débordé, DG de PME sans direction financière, filiale qui remonte un reporting groupe. Le signal d’achat : clôture en retard, balance qui ne tombe pas, banque qui demande des comptes certifiables.",
  },
  {
    line: "comptabilite",
    category: "Argumentaires",
    title: "Pitch tenue et révision",
    body: "Nous reprenons la balance, nous justifions les comptes sensibles (banque, clients, fournisseurs, immobilisations, TVA) et nous sortons des états SYSCOHADA exploitables : bilan, compte de résultat, notes annexes, TAFIRE. La tenue mensuelle évite la clôture de crise.",
  },
  {
    line: "comptabilite",
    category: "Questions de découverte",
    title: "Questions chef comptable",
    body: "Quel logiciel ? La balance est-elle arrêtée chaque mois ? Dernier rapprochement bancaire ? Inventaire des immobilisations à jour ? Qui signe les états avant l’assemblée ? Y a-t-il un reporting groupe en plus du SYSCOHADA ?",
  },
  {
    line: "comptabilite",
    category: "Offres types",
    title: "Mission type",
    body: "Reprise de balances et lettrage. Tenue mensuelle. Révision annuelle et liasse. Situation intermédiaire pour la banque ou le groupe. Accompagnement du dossier d’assemblée générale. Honoraires en FCFA, périmètre et calendrier écrits.",
  },
  {
    line: "comptabilite",
    category: "Emails",
    title: "Mail situation ou clôture",
    body: "Objet : Clôture SYSCOHADA — 20 min pour cadrer balance, banque et immobilisations.\n\nBonjour,\n\nNous accompagnons des DAF sur la tenue mensuelle et la révision de clôture (rapprochements, cut-off, états financiers et TAFIRE).\n\nJe vous propose un échange de 20 minutes pour voir où en est votre exercice. Deux créneaux : mardi 9 h ou jeudi 16 h.\n\nBien cordialement",
  },
  {
    line: "comptabilite",
    category: "WhatsApp",
    title: "Relance courte",
    body: "Bonjour, suite à notre échange : nous pouvons reprendre la balance et les rapprochements bancaires avant la clôture. Je vous propose jeudi 10 h, 20 minutes. Cela vous va ?",
  },

  lex(
    "fiscalite",
    "Impôts, TVA et contrôle",
    "Vocabulaire DGI et direction financière. On parle de sécurisation et de calendrier, pas d’« astuces » pour payer moins.",
    [
      { term: "Impôt sur les sociétés (IS)", def: "Impôt dû sur le résultat fiscal de la société, distinct du résultat comptable." },
      { term: "Acompte provisionnel", def: "Versement d’IS en cours d’année, calculé sur l’impôt de l’exercice précédent." },
      { term: "TVA collectée", def: "Taxe facturée aux clients et à reverser." },
      { term: "TVA déductible", def: "Taxe payée sur les achats, déductible si la dépense est éligible et la pièce régulière." },
      { term: "Crédit de TVA", def: "Excédent de TVA déductible : à reporter ou à demander en remboursement." },
      { term: "Prorata de déduction", def: "Quote-part de TVA déductible quand l’activité mélange opérations taxables et exonérées." },
      { term: "IRPP", def: "Impôt sur le revenu des personnes physiques, y compris la retenue sur salaires." },
      { term: "Retenue à la source", def: "Impôt prélevé par le payeur au moment du règlement (prestations, non-résidents, salaires)." },
      { term: "Liasse fiscale", def: "Déclaration de résultat et états annexes déposés auprès de l’administration." },
      { term: "Quitus fiscal", def: "Attestation que la société est en règle avec ses obligations déclaratives et de paiement." },
      { term: "Contrôle fiscal", def: "Vérification par l’administration des déclarations, pièces et comptes." },
      { term: "Redressement", def: "Rectification d’impôt proposée ou notifiée à l’issue du contrôle." },
    ],
  ),
  {
    line: "fiscalite",
    category: "Cibles prioritaires",
    title: "Qui porte le risque fiscal",
    body: "DAF, directeur fiscal, DG de filiale, groupe avec flux intra-groupe, société qui cumule un crédit de TVA ou des acomptes mal calés. Signal : contrôle annoncé, quitus demandé par une banque ou un marché public, retard de liasse.",
  },
  {
    line: "fiscalite",
    category: "Argumentaires",
    title: "Pitch sécurisation fiscale",
    body: "Nous recollons le résultat comptable au résultat fiscal, nous vérifions TVA collectée, TVA déductible, prorata, retenues à la source et acomptes d’IS. L’objectif est un calendrier tenu et un dossier défendable en cas de contrôle, pas une optimisation opaque.",
  },
  {
    line: "fiscalite",
    category: "Questions de découverte",
    title: "Questions DAF",
    body: "Date de dépôt de la dernière liasse ? Acomptes provisionnels calés sur le dernier IS ? Crédit de TVA en suspens ? Retenues à la source sur les prestataires étrangers ? Contrôle en cours ou passé ? Le quitus est-il à jour ?",
  },
  {
    line: "fiscalite",
    category: "Offres types",
    title: "Mission type",
    body: "Revue de conformité IS et TVA. Calendrier fiscal annuel. Assistance à la liasse. Préparation ou accompagnement d’un contrôle. Cartographie des retenues à la source. Chiffrage en FCFA, avec la liste des impôts couverts.",
  },
  {
    line: "fiscalite",
    category: "Emails",
    title: "Mail avant échéance",
    body: "Objet : Acomptes d’IS et TVA — 20 min avant la prochaine échéance.\n\nBonjour,\n\nNous aidons les DAF à sécuriser l’IS, la TVA et les retenues à la source, et à préparer un dossier lisible en cas de contrôle.\n\nPuis-je vous proposer mardi ou jeudi, 20 minutes, pour voir vos prochaines échéances ?\n\nBien cordialement",
  },
  {
    line: "fiscalite",
    category: "WhatsApp",
    title: "Relance échéance",
    body: "Bonjour, la prochaine échéance d’acompte ou de TVA approche. Nous pouvons vérifier l’assiette en 20 minutes jeudi. Je vous bloque le créneau ?",
  },

  lex(
    "audit",
    "Mission, risques et opinion",
    "Vocabulaire à tenir devant un conseil, un commissaire ou une banque. On nomme le niveau d’assurance, pas un simple « contrôle des comptes ».",
    [
      { term: "Commissariat aux comptes", def: "Mission légale de certification des comptes, distincte de la tenue." },
      { term: "Audit contractuel", def: "Mission convenue par contrat, hors obligation légale de commissariat." },
      { term: "Seuil de signification", def: "Montant à partir duquel une erreur peut influencer le lecteur des comptes." },
      { term: "Risque d’anomalies significatives", def: "Risque qu’une erreur importante existe et ne soit pas détectée par les contrôles." },
      { term: "Assertions d’audit", def: "Ce que l’on vérifie sur un solde : existence, exhaustivité, évaluation, propriété, présentation." },
      { term: "Circularisation", def: "Confirmation directe demandée aux tiers : banques, clients, avocats, fournisseurs." },
      { term: "Lettre d’affirmation", def: "Déclaration écrite de la direction sur l’exhaustivité des informations données à l’auditeur." },
      { term: "Opinion sans réserve", def: "Certification : les comptes donnent une image fidèle, sans exception." },
      { term: "Opinion avec réserve", def: "Certification assortie d’un désaccord ou d’une limitation, clairement circonscrits." },
      { term: "Continuité d’exploitation", def: "Capacité de la société à poursuivre son activité sur les douze mois à venir." },
      { term: "Piste d’audit", def: "Chaîne pièce → écriture → compte → état, reconstituable par un tiers." },
      { term: "Contrôle interne", def: "Dispositifs qui préviennent ou détectent les erreurs : séparation des tâches, visas, rapprochements." },
    ],
  ),
  {
    line: "audit",
    category: "Cibles prioritaires",
    title: "Qui a besoin d’une opinion",
    body: "Conseil d’administration, DG de filiale, actionnaire groupe, banque qui exige des comptes certifiés, société qui change de commissaire aux comptes. Signal : lettre de mission absente, faiblesses de contrôle interne, délai de certification dépassé.",
  },
  {
    line: "audit",
    category: "Argumentaires",
    title: "Pitch certification",
    body: "La tenue produit les comptes. L’audit dit s’ils sont fiables. Nous cadrons le seuil de signification, nous testons les assertions sur les comptes sensibles et nous formulons une opinion. Un audit contractuel peut précéder un commissariat, ou rassurer une banque sans attendre l’obligation légale.",
  },
  {
    line: "audit",
    category: "Questions de découverte",
    title: "Questions avant lettre de mission",
    body: "Commissaire en place ou premier mandat ? Comptes établis en SYSCOHADA et arrêtés à quelle date ? Circularisations banque déjà faites ? Séparation des tâches sur les paiements ? Sujet de continuité d’exploitation ? Quel lecteur : assemblée, groupe ou banque ?",
  },
  {
    line: "audit",
    category: "Offres types",
    title: "Mission type",
    body: "Commissariat aux comptes. Audit contractuel de clôture. Revue limitée d’une situation intermédiaire. Diagnostic du contrôle interne (achats, ventes, paie, trésorerie). Restitution : rapport, points d’audit, recommandations classées.",
  },
  {
    line: "audit",
    category: "Emails",
    title: "Mail prise de mandat",
    body: "Objet : Certification des comptes — cadrage du périmètre en 20 min.\n\nBonjour,\n\nNous intervenons en commissariat aux comptes et en audit contractuel : seuil de signification, tests sur les comptes clés, opinion écrite.\n\nJe vous propose un échange pour voir si vous êtes sur un premier mandat, un appel d’offres ou une demande de la banque.\n\nBien cordialement",
  },
  {
    line: "audit",
    category: "WhatsApp",
    title: "Relance mandat",
    body: "Bonjour, pour le mandat d’audit nous avons besoin de la date d’arrêté et du nom du lecteur des comptes (assemblée, groupe ou banque). 20 minutes jeudi, cela vous convient ?",
  },

  lex(
    "juridique",
    "Sociétés, contrats et actes",
    "Vocabulaire OHADA à utiliser avec un dirigeant ou un fondateur. On nomme l’acte et le registre, pas un « papier à faire signer ».",
    [
      { term: "AUSCGIE", def: "Acte uniforme OHADA relatif au droit des sociétés commerciales et du groupement d’intérêt économique." },
      { term: "RCCM", def: "Registre du commerce et du crédit mobilier : immatriculation et publicité des sociétés." },
      { term: "Statuts", def: "Contrat fondateur : forme, capital, objet, pouvoirs de direction, règles d’assemblées." },
      { term: "Assemblée générale", def: "Réunion des associés pour approuver les comptes, affecter le résultat ou modifier les statuts." },
      { term: "Procès-verbal", def: "Écrit qui constate les décisions de l’assemblée ou de la gérance." },
      { term: "Cession de parts sociales", def: "Transmission des parts d’une SARL, soumise à agrément et à enregistrement." },
      { term: "Augmentation de capital", def: "Apport nouveau qui modifie le capital et, souvent, les statuts." },
      { term: "Bail commercial", def: "Contrat de location du local d’exploitation, avec durée, loyer et destination." },
      { term: "Fonds de commerce", def: "Ensemble d’éléments d’exploitation (clientèle, enseigne, droit au bail) cessible." },
      { term: "Sûretés", def: "Garanties OHADA : caution, gage, nantissement, hypothèque." },
      { term: "Mise en demeure", def: "Courrier qui constate un manquement et fixe un délai avant action." },
      { term: "Injonction de payer", def: "Procédure pour recouvrer une créance certaine, liquide et exigible." },
    ],
  ),
  {
    line: "juridique",
    category: "Cibles prioritaires",
    title: "Qui signe les actes",
    body: "DG, fondateur, directeur juridique absent, groupe qui ouvre une filiale à Libreville ou Port-Gentil. Signal : statuts qui ne sont plus à jour, cession verbale, bail qui expire, impayé client sans mise en demeure, marché qui exige une attestation RCCM.",
  },
  {
    line: "juridique",
    category: "Argumentaires",
    title: "Pitch secrétariat et contrats",
    body: "Le contentieux coûte plus cher que l’acte fait à temps. Nous tenons le secrétariat juridique (assemblées, procès-verbaux, RCCM), nous relisons statuts et baux, et nous cadrons les contrats de prestation avant signature. Chaque acte cite la bonne base : AUSCGIE, sûretés, bail, cession.",
  },
  {
    line: "juridique",
    category: "Questions de découverte",
    title: "Questions dirigeant",
    body: "Forme sociale et date des derniers statuts ? Assemblée de l’exercice tenu ? Pacte d’associés ? Bail : échéance et destination ? Contrats cadres avec les donneurs d’ordre ? Contentieux ou mises en demeure en cours ?",
  },
  {
    line: "juridique",
    category: "Offres types",
    title: "Mission type",
    body: "Secrétariat juridique annuel : approbation des comptes, PV, dépôt. Revue de statuts. Pacte ou cession de parts. Bail commercial. Contrat de prestation et conditions de paiement. Mise en demeure et suivi de recouvrement.",
  },
  {
    line: "juridique",
    category: "Emails",
    title: "Mail secrétariat annuel",
    body: "Objet : Approbation des comptes — actes et RCCM.\n\nBonjour,\n\nNous préparons les assemblées, les procès-verbaux et les formalités RCCM, et nous relisons statuts et contrats avant qu’un litige ne fige la décision.\n\n20 minutes pour voir si votre exercice est déjà approuvé ? Mardi ou jeudi.\n\nBien cordialement",
  },
  {
    line: "juridique",
    category: "WhatsApp",
    title: "Relance acte",
    body: "Bonjour, pour l’assemblée il nous manque la date souhaitée et la dernière version des statuts. Je vous propose jeudi 10 h pour caler le calendrier des actes.",
  },

  lex(
    "rh",
    "Paie, contrats et charges sociales",
    "Vocabulaire DRH et paie au Gabon. On distingue le bulletin, les organismes sociaux et le contrat.",
    [
      { term: "Bulletin de paie", def: "Document mensuel : salaire brut, retenues, net à payer, cumuls." },
      { term: "Masse salariale", def: "Total des rémunérations brutes et charges, base des budgets et des audits sociaux." },
      { term: "CNSS", def: "Caisse nationale de sécurité sociale : cotisations et prestations sociales." },
      { term: "CNAMGS", def: "Caisse d’assurance maladie : couverture santé et cotisations associées." },
      { term: "IRPP sur salaires", def: "Retenue d’impôt sur le revenu opérée sur les traitements et salaires." },
      { term: "CDI", def: "Contrat à durée indéterminée, forme de droit commun." },
      { term: "CDD", def: "Contrat à durée déterminée, réservé aux cas prévus et écrit." },
      { term: "Période d’essai", def: "Phase initiale pendant laquelle chaque partie peut rompre selon les règles du code du travail." },
      { term: "Préavis", def: "Délai à respecter avant la fin effective du contrat, sauf faute ou dispense." },
      { term: "Congés payés", def: "Droit à congé acquis au titre du travail effectif, à solder et à provisionner." },
      { term: "Heures supplémentaires", def: "Heures au-delà de la durée légale, majorées et suivies." },
      { term: "Solde de tout compte", def: "Récapitulatif des sommes versées à la rupture : salaire, congés, indemnités." },
    ],
  ),
  {
    line: "rh",
    category: "Cibles prioritaires",
    title: "Qui porte la paie",
    body: "DRH, DAF qui signe les bulletins sans service RH, PME en croissance, employeur avec expatriés ou nombreux CDD. Signal : retards CNSS ou CNAMGS, bulletins contestés, contrats non signés, contentieux devant le tribunal du travail.",
  },
  {
    line: "rh",
    category: "Argumentaires",
    title: "Pitch paie et conformité sociale",
    body: "Un bulletin faux devient une dette CNSS, CNAMGS et IRPP. Nous reprenons la masse salariale, les contrats (CDI, CDD, période d’essai, préavis) et le calendrier des déclarations. La paie externalisée laisse au DRH le dialogue social, pas la saisie.",
  },
  {
    line: "rh",
    category: "Questions de découverte",
    title: "Questions DRH",
    body: "Effectif CDI / CDD ? Logiciel de paie ? Dernières déclarations CNSS et CNAMGS ? Contrats de travail signés et à jour ? Contentieux ou inspections en cours ? Qui valide les variables chaque mois ?",
  },
  {
    line: "rh",
    category: "Offres types",
    title: "Mission type",
    body: "Externalisation de la paie. Audit de conformité : contrats, bulletins, cotisations. Reprise d’historique. Référentiel de postes et masse salariale budgétée. Accompagnement d’une rupture : préavis, solde de tout compte, documents de fin de contrat.",
  },
  {
    line: "rh",
    category: "Emails",
    title: "Mail DRH ou DAF",
    body: "Objet : Paie, CNSS et contrats — 20 min de cadrage.\n\nBonjour,\n\nNous reprenons les bulletins, les cotisations CNSS et CNAMGS, et la conformité des CDI et CDD.\n\nJe vous propose un échange de 20 minutes pour voir votre effectif et votre calendrier de paie.\n\nBien cordialement",
  },
  {
    line: "rh",
    category: "WhatsApp",
    title: "Relance paie",
    body: "Bonjour, nous pouvons regarder vos bulletins et les échéances CNSS jeudi 10 h (20 min). Vous préférez avec le DRH ou le DAF ?",
  },

  lex(
    "formation",
    "Dispositif, publics et évaluation",
    "Vocabulaire à utiliser avec un responsable formation. On parle d’objectifs et de publics, pas d’une « journée de sensibilisation » sans suite.",
    [
      { term: "Ingénierie pédagogique", def: "Conception du parcours : besoins, objectifs, séquences, exercices, évaluation." },
      { term: "Intra-entreprise", def: "Session réservée aux équipes d’un seul employeur, sur ses cas." },
      { term: "Inter-entreprises", def: "Session ouverte à plusieurs sociétés, utile pour un public trop petit en intra." },
      { term: "Cahier des charges", def: "Document qui fixe publics, objectifs, durée, prérequis et critères de réussite." },
      { term: "Objectif pédagogique", def: "Ce que le participant sait faire à la fin, observable, pas un thème vague." },
      { term: "Évaluation à chaud", def: "Mesure en fin de session : satisfaction, acquis immédiats, points à retravailler." },
      { term: "Évaluation à froid", def: "Mesure plusieurs semaines après : ce qui est vraiment appliqué au poste." },
      { term: "Mise en situation", def: "Exercice sur un cas de l’entreprise, plutôt qu’un exposé descendant." },
      { term: "Attestation de fin de formation", def: "Justificatif nominatif : intitulé, dates, durée, objectifs couverts." },
      { term: "Plan de développement des compétences", def: "Programmation annuelle des formations par métier et par écart de compétence." },
      { term: "Référentiel de compétences", def: "Liste des savoir-faire attendus sur un poste, base du diagnostic." },
    ],
  ),
  {
    line: "formation",
    category: "Cibles prioritaires",
    title: "Qui achète une session",
    body: "DRH, responsable formation, DG qui veut faire monter des managers ou des comptables, DAF qui prépare une clôture avec une équipe junior. Signal : pas de plan de développement des compétences, formations « catalogue » sans mise en situation, turn-over sur la paie ou la compta.",
  },
  {
    line: "formation",
    category: "Argumentaires",
    title: "Pitch intra sur cas réels",
    body: "La formation est utile quand elle part du référentiel du poste et des pièces de l’entreprise. Nous construisons un intra : cahier des charges, objectifs pédagogiques, mises en situation (SYSCOHADA, TVA, paie, contrats), puis évaluation à chaud et à froid. Une attestation seule ne prouve pas le transfert.",
  },
  {
    line: "formation",
    category: "Questions de découverte",
    title: "Questions responsable formation",
    body: "Quels métiers sont en écart ? Intra ou inter ? Durée réelle disponible ? Les managers peuvent-ils apporter leurs dossiers ? Comment évaluez-vous aujourd’hui, à chaud seulement ? Budget et nombre de participants ?",
  },
  {
    line: "formation",
    category: "Offres types",
    title: "Parcours types",
    body: "Diagnostic de besoins (entretiens + référentiel). Intra 2 jours : clôture SYSCOHADA, TVA et liasse, ou paie CNSS/CNAMGS. Atelier managers : lire un bilan et un compte de résultat. Séminaire juridique : statuts, assemblées, contrats. Attestations et bilan à froid à 6 semaines.",
  },
  {
    line: "formation",
    category: "Emails",
    title: "Mail intra",
    body: "Objet : Intra sur vos dossiers — cadrage des objectifs en 20 min.\n\nBonjour,\n\nNous concevons des intra à partir de vos écarts de compétences (comptabilité, fiscalité, paie, actes juridiques), avec mise en situation et évaluation à froid.\n\n20 minutes pour identifier le public et le résultat attendu ?\n\nBien cordialement",
  },
  {
    line: "formation",
    category: "WhatsApp",
    title: "Relance session",
    body: "Bonjour, pour l’intra il me faut le public (comptables, managers ou RH) et la date visée. Je vous propose jeudi 10 h pour figer les objectifs pédagogiques.",
  },

  lex(
    "conseil",
    "Diagnostic, pilotage et décision",
    "Vocabulaire COMEX et direction générale. On vend une décision étayée, pas une « étude » sans suite.",
    [
      { term: "Diagnostic organisationnel", def: "Constat court : ce qui bloque, preuves, et ce qui peut attendre." },
      { term: "Schéma directeur", def: "Cible à 18–36 mois : organisation, outils, compétences, jalons." },
      { term: "Contrôle de gestion", def: "Suivi des écarts budget / réel et des coûts, pour décider en cours d’année." },
      { term: "Tableau de bord", def: "Peu d’indicateurs, à date fixe, lus par la direction." },
      { term: "Indicateur de pilotage", def: "Mesure qui déclenche une action, distincte d’une statistique de reporting." },
      { term: "Conduite du changement", def: "Plan pour faire adopter un nouveau processus : sponsors, relais, rituels." },
      { term: "Gouvernance", def: "Qui décide, sur quelles informations, à quel rythme (comité, délégations)." },
      { term: "Feuille de route", def: "Actions datées, responsables nommés, charge et gain attendu." },
      { term: "Processus métier", def: "Enchaînement réel du travail (devis → facture → encaissement), pas l’organigramme." },
      { term: "Quick win", def: "Action de moins de 30 jours qui prouve le diagnostic avant le grand chantier." },
      { term: "Sponsor", def: "Dirigeant qui tranche et protège le chantier, distinct du chef de projet." },
    ],
  ),
  {
    line: "conseil",
    category: "Cibles prioritaires",
    title: "Qui commande un diagnostic",
    body: "DG, COMEX, DAF en prise de poste, groupe qui aligne ses filiales. Signal : décisions qui reviennent chaque comité, pas de tableau de bord, clôture et commercial qui ne se parlent pas, projet d’outil lancé sans processus cible.",
  },
  {
    line: "conseil",
    category: "Argumentaires",
    title: "Pitch diagnostic puis feuille de route",
    body: "Quinze jours pour un diagnostic organisationnel : processus, gouvernance, indicateurs. Ensuite une feuille de route avec quick wins, et seulement si besoin un schéma directeur. Nous ne livrons pas un rapport que personne ne pilote : chaque action a un sponsor et une date.",
  },
  {
    line: "conseil",
    category: "Questions de découverte",
    title: "Questions DG",
    body: "Quelle décision est en souffrance depuis plus de trois mois ? Quels chiffres voyez-vous chaque mois ? Qui est le sponsor si nous intervenons ? Qu’est-ce qui doit bouger en 30 jours, et qu’est-ce qui peut attendre le schéma directeur ?",
  },
  {
    line: "conseil",
    category: "Offres types",
    title: "Mission type",
    body: "Diagnostic 15 jours, restitution COMEX. Installation d’un tableau de bord et d’un rituel de contrôle de gestion. Feuille de route 90 jours. Schéma directeur sur un périmètre nommé (finance, commercial, organisation). Honoraires en FCFA, livrables listés.",
  },
  {
    line: "conseil",
    category: "Emails",
    title: "Mail DG",
    body: "Objet : Diagnostic 15 jours — la décision qui bloque.\n\nBonjour,\n\nNous cadrons un diagnostic court (processus, gouvernance, indicateurs) puis une feuille de route avec des quick wins, avant tout schéma directeur.\n\n20 minutes pour identifier la décision qui n’avance pas ?\n\nBien cordialement",
  },
  {
    line: "conseil",
    category: "WhatsApp",
    title: "Relance diagnostic",
    body: "Bonjour, je vous propose jeudi 10 h pour cerner la décision qui bloque et voir si un diagnostic de 15 jours est le bon format.",
  },
];
