-- Champs alignés sur la fiche unique d'enregistrement ANPI-Gabon
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "sigle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "shareCapital" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "cnss" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "cnamgs" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "activity" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "activityDetail" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "representativeTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "anpiNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "anpiDate" TEXT NOT NULL DEFAULT '';
