/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CompteSupprimeRouteImport } from './routes/compte-supprime'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as QuotasRouteImport } from './routes/quotas'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppArchiveRouteImport } from './routes/_app.archive'
import { Route as AppBilanRouteImport } from './routes/_app.bilan'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentationRouteImport } from './routes/_app.documentation'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppLettreRouteImport } from './routes/_app.lettre'
import { Route as AppMailsRouteImport } from './routes/_app.mails'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPolesRouteImport } from './routes/_app.poles'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppQuotationsRouteImport } from './routes/_app.quotations'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as ProspectionIndexRouteImport } from './routes/prospection.index'
import { Route as ProspectionActionsRouteImport } from './routes/prospection.actions'
import { Route as ProspectionActivitesRouteImport } from './routes/prospection.activites'
import { Route as ProspectionAdminRouteImport } from './routes/prospection.admin'
import { Route as ProspectionAgendaRouteImport } from './routes/prospection.agenda'
import { Route as ProspectionBibliothequeRouteImport } from './routes/prospection.bibliotheque'
import { Route as ProspectionBudgetRouteImport } from './routes/prospection.budget'
import { Route as ProspectionClientsRouteImport } from './routes/prospection.clients'
import { Route as ProspectionEquipeRouteImport } from './routes/prospection.equipe'
import { Route as ProspectionImportRouteImport } from './routes/prospection.import'
import { Route as ProspectionKpiRouteImport } from './routes/prospection.kpi'
import { Route as ProspectionNotificationsRouteImport } from './routes/prospection.notifications'
import { Route as ProspectionObjectifsRouteImport } from './routes/prospection.objectifs'
import { Route as ProspectionOpportunitesRouteImport } from './routes/prospection.opportunites'
import { Route as ProspectionPipelineRouteImport } from './routes/prospection.pipeline'
import { Route as ProspectionPisteRouteImport } from './routes/prospection.piste'
import { Route as ProspectionPistesRouteImport } from './routes/prospection.pistes'
import { Route as ProspectionPortGentilRouteImport } from './routes/prospection.port-gentil'
import { Route as ProspectionPortefeuilleRouteImport } from './routes/prospection.portefeuille'
import { Route as ProspectionProspectsRouteImport } from './routes/prospection.prospects'
import { Route as ProspectionStrategiquesRouteImport } from './routes/prospection.strategiques'
import { Route as AppClientsIndexRouteImport } from './routes/_app.clients.index'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'
import { Route as AppClientsNewRouteImport } from './routes/_app.clients.new'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppInvoicesNewRouteImport } from './routes/_app.invoices.new'
import { Route as AppLettersIndexRouteImport } from './routes/_app.letters.index'
import { Route as AppLettersIdRouteImport } from './routes/_app.letters.$id'
import { Route as AppLettersNewRouteImport } from './routes/_app.letters.new'
import { Route as AppLettreIndexRouteImport } from './routes/_app.lettre.index'
import { Route as AppLettreIdRouteImport } from './routes/_app.lettre.$id'
import { Route as AppLettreNewRouteImport } from './routes/_app.lettre.new'
import { Route as AppLettrePublipostageRouteImport } from './routes/_app.lettre.publipostage'
import { Route as AppQuotationsIndexRouteImport } from './routes/_app.quotations.index'
import { Route as AppQuotationsIdRouteImport } from './routes/_app.quotations.$id'
import { Route as AppQuotationsNewRouteImport } from './routes/_app.quotations.new'
import { Route as ApiCronBillingRouteImport } from './routes/api/cron.billing'
import { Route as ApiStaffSyncRouteImport } from './routes/api/staff.sync'
import { Route as ProspectionClientsIndexRouteImport } from './routes/prospection.clients.index'
import { Route as ProspectionClientsIdRouteImport } from './routes/prospection.clients.$id'
import { Route as ProspectionProspectsIndexRouteImport } from './routes/prospection.prospects.index'
import { Route as ProspectionProspectsIdRouteImport } from './routes/prospection.prospects.$id'
import { Route as AppInvoicesIdEditRouteImport } from './routes/_app.invoices.$id.edit'
import { Route as AppQuotationsIdEditRouteImport } from './routes/_app.quotations.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteSupprimeRoute = CompteSupprimeRouteImport.update({
  id: '/compte-supprime',
  path: '/compte-supprime',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotasRoute = QuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppBilanRoute = AppBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLettreRoute = AppLettreRouteImport.update({
  id: '/lettre',
  path: '/lettre',
  getParentRoute: () => AppRoute,
} as any)
const AppMailsRoute = AppMailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPolesRoute = AppPolesRouteImport.update({
  id: '/poles',
  path: '/poles',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionIndexRoute = ProspectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionActionsRoute = ProspectionActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionActivitesRoute = ProspectionActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionAdminRoute = ProspectionAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionAgendaRoute = ProspectionAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionBibliothequeRoute = ProspectionBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionBudgetRoute = ProspectionBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionClientsRoute = ProspectionClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionEquipeRoute = ProspectionEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionImportRoute = ProspectionImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionKpiRoute = ProspectionKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionNotificationsRoute =
  ProspectionNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProspectionRoute,
  } as any)
const ProspectionObjectifsRoute = ProspectionObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionOpportunitesRoute = ProspectionOpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionPipelineRoute = ProspectionPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionPisteRoute = ProspectionPisteRouteImport.update({
  id: '/piste',
  path: '/piste',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionPistesRoute = ProspectionPistesRouteImport.update({
  id: '/pistes',
  path: '/pistes',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionPortGentilRoute = ProspectionPortGentilRouteImport.update({
  id: '/port-gentil',
  path: '/port-gentil',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionPortefeuilleRoute = ProspectionPortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionProspectsRoute = ProspectionProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => ProspectionRoute,
} as any)
const ProspectionStrategiquesRoute = ProspectionStrategiquesRouteImport.update({
  id: '/strategiques',
  path: '/strategiques',
  getParentRoute: () => ProspectionRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppLettersIndexRoute = AppLettersIndexRouteImport.update({
  id: '/letters/',
  path: '/letters/',
  getParentRoute: () => AppRoute,
} as any)
const AppLettersIdRoute = AppLettersIdRouteImport.update({
  id: '/letters/$id',
  path: '/letters/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLettersNewRoute = AppLettersNewRouteImport.update({
  id: '/letters/new',
  path: '/letters/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLettreIndexRoute = AppLettreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLettreRoute,
} as any)
const AppLettreIdRoute = AppLettreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLettreRoute,
} as any)
const AppLettreNewRoute = AppLettreNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLettreRoute,
} as any)
const AppLettrePublipostageRoute = AppLettrePublipostageRouteImport.update({
  id: '/publipostage',
  path: '/publipostage',
  getParentRoute: () => AppLettreRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotationsRoute,
} as any)
const AppQuotationsIdRoute = AppQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQuotationsRoute,
} as any)
const AppQuotationsNewRoute = AppQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuotationsRoute,
} as any)
const ApiCronBillingRoute = ApiCronBillingRouteImport.update({
  id: '/api/cron/billing',
  path: '/api/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffSyncRoute = ApiStaffSyncRouteImport.update({
  id: '/api/staff/sync',
  path: '/api/staff/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionClientsIndexRoute = ProspectionClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspectionClientsRoute,
} as any)
const ProspectionClientsIdRoute = ProspectionClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectionClientsRoute,
} as any)
const ProspectionProspectsIndexRoute =
  ProspectionProspectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProspectionProspectsRoute,
  } as any)
const ProspectionProspectsIdRoute = ProspectionProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectionProspectsRoute,
} as any)
const AppInvoicesIdEditRoute = AppInvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppInvoicesIdRoute,
} as any)
const AppQuotationsIdEditRoute = AppQuotationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppQuotationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compte-supprime': typeof CompteSupprimeRoute
  '/equipe': typeof EquipeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prospection': typeof ProspectionRouteWithChildren
  '/quotas': typeof QuotasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AppArchiveRoute
  '/bilan': typeof AppBilanRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentation': typeof AppDocumentationRoute
  '/documents': typeof AppDocumentsRoute
  '/home': typeof AppHomeRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/lettre': typeof AppLettreRouteWithChildren
  '/mails': typeof AppMailsRoute
  '/notifications': typeof AppNotificationsRoute
  '/poles': typeof AppPolesRoute
  '/profile': typeof AppProfileRoute
  '/quotations': typeof AppQuotationsRouteWithChildren
  '/search': typeof AppSearchRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/prospection/actions': typeof ProspectionActionsRoute
  '/prospection/activites': typeof ProspectionActivitesRoute
  '/prospection/admin': typeof ProspectionAdminRoute
  '/prospection/agenda': typeof ProspectionAgendaRoute
  '/prospection/bibliotheque': typeof ProspectionBibliothequeRoute
  '/prospection/budget': typeof ProspectionBudgetRoute
  '/prospection/clients': typeof ProspectionClientsRouteWithChildren
  '/prospection/equipe': typeof ProspectionEquipeRoute
  '/prospection/import': typeof ProspectionImportRoute
  '/prospection/kpi': typeof ProspectionKpiRoute
  '/prospection/notifications': typeof ProspectionNotificationsRoute
  '/prospection/objectifs': typeof ProspectionObjectifsRoute
  '/prospection/opportunites': typeof ProspectionOpportunitesRoute
  '/prospection/pipeline': typeof ProspectionPipelineRoute
  '/prospection/piste': typeof ProspectionPisteRoute
  '/prospection/pistes': typeof ProspectionPistesRoute
  '/prospection/port-gentil': typeof ProspectionPortGentilRoute
  '/prospection/portefeuille': typeof ProspectionPortefeuilleRoute
  '/prospection/prospects': typeof ProspectionProspectsRouteWithChildren
  '/prospection/strategiques': typeof ProspectionStrategiquesRoute
  '/prospection/': typeof ProspectionIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/invoices/$id': typeof AppInvoicesIdRouteWithChildren
  '/invoices/new': typeof AppInvoicesNewRoute
  '/letters/$id': typeof AppLettersIdRoute
  '/letters/new': typeof AppLettersNewRoute
  '/lettre/$id': typeof AppLettreIdRoute
  '/lettre/new': typeof AppLettreNewRoute
  '/lettre/publipostage': typeof AppLettrePublipostageRoute
  '/quotations/$id': typeof AppQuotationsIdRouteWithChildren
  '/quotations/new': typeof AppQuotationsNewRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/staff/sync': typeof ApiStaffSyncRoute
  '/prospection/clients/$id': typeof ProspectionClientsIdRoute
  '/prospection/prospects/$id': typeof ProspectionProspectsIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/letters/': typeof AppLettersIndexRoute
  '/lettre/': typeof AppLettreIndexRoute
  '/quotations/': typeof AppQuotationsIndexRoute
  '/prospection/clients/': typeof ProspectionClientsIndexRoute
  '/prospection/prospects/': typeof ProspectionProspectsIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/quotations/$id/edit': typeof AppQuotationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compte-supprime': typeof CompteSupprimeRoute
  '/equipe': typeof EquipeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/quotas': typeof QuotasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AppArchiveRoute
  '/bilan': typeof AppBilanRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentation': typeof AppDocumentationRoute
  '/documents': typeof AppDocumentsRoute
  '/home': typeof AppHomeRoute
  '/mails': typeof AppMailsRoute
  '/notifications': typeof AppNotificationsRoute
  '/poles': typeof AppPolesRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/prospection/actions': typeof ProspectionActionsRoute
  '/prospection/activites': typeof ProspectionActivitesRoute
  '/prospection/admin': typeof ProspectionAdminRoute
  '/prospection/agenda': typeof ProspectionAgendaRoute
  '/prospection/bibliotheque': typeof ProspectionBibliothequeRoute
  '/prospection/budget': typeof ProspectionBudgetRoute
  '/prospection/equipe': typeof ProspectionEquipeRoute
  '/prospection/import': typeof ProspectionImportRoute
  '/prospection/kpi': typeof ProspectionKpiRoute
  '/prospection/notifications': typeof ProspectionNotificationsRoute
  '/prospection/objectifs': typeof ProspectionObjectifsRoute
  '/prospection/opportunites': typeof ProspectionOpportunitesRoute
  '/prospection/pipeline': typeof ProspectionPipelineRoute
  '/prospection/piste': typeof ProspectionPisteRoute
  '/prospection/pistes': typeof ProspectionPistesRoute
  '/prospection/port-gentil': typeof ProspectionPortGentilRoute
  '/prospection/portefeuille': typeof ProspectionPortefeuilleRoute
  '/prospection/strategiques': typeof ProspectionStrategiquesRoute
  '/prospection': typeof ProspectionIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/invoices/$id': typeof AppInvoicesIdRouteWithChildren
  '/invoices/new': typeof AppInvoicesNewRoute
  '/letters/$id': typeof AppLettersIdRoute
  '/letters/new': typeof AppLettersNewRoute
  '/lettre/$id': typeof AppLettreIdRoute
  '/lettre/new': typeof AppLettreNewRoute
  '/lettre/publipostage': typeof AppLettrePublipostageRoute
  '/quotations/$id': typeof AppQuotationsIdRouteWithChildren
  '/quotations/new': typeof AppQuotationsNewRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/staff/sync': typeof ApiStaffSyncRoute
  '/prospection/clients/$id': typeof ProspectionClientsIdRoute
  '/prospection/prospects/$id': typeof ProspectionProspectsIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/letters': typeof AppLettersIndexRoute
  '/lettre': typeof AppLettreIndexRoute
  '/quotations': typeof AppQuotationsIndexRoute
  '/prospection/clients': typeof ProspectionClientsIndexRoute
  '/prospection/prospects': typeof ProspectionProspectsIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/quotations/$id/edit': typeof AppQuotationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/compte-supprime': typeof CompteSupprimeRoute
  '/equipe': typeof EquipeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prospection': typeof ProspectionRouteWithChildren
  '/quotas': typeof QuotasRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/bilan': typeof AppBilanRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/lettre': typeof AppLettreRouteWithChildren
  '/_app/mails': typeof AppMailsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/poles': typeof AppPolesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quotations': typeof AppQuotationsRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/prospection/actions': typeof ProspectionActionsRoute
  '/prospection/activites': typeof ProspectionActivitesRoute
  '/prospection/admin': typeof ProspectionAdminRoute
  '/prospection/agenda': typeof ProspectionAgendaRoute
  '/prospection/bibliotheque': typeof ProspectionBibliothequeRoute
  '/prospection/budget': typeof ProspectionBudgetRoute
  '/prospection/clients': typeof ProspectionClientsRouteWithChildren
  '/prospection/equipe': typeof ProspectionEquipeRoute
  '/prospection/import': typeof ProspectionImportRoute
  '/prospection/kpi': typeof ProspectionKpiRoute
  '/prospection/notifications': typeof ProspectionNotificationsRoute
  '/prospection/objectifs': typeof ProspectionObjectifsRoute
  '/prospection/opportunites': typeof ProspectionOpportunitesRoute
  '/prospection/pipeline': typeof ProspectionPipelineRoute
  '/prospection/piste': typeof ProspectionPisteRoute
  '/prospection/pistes': typeof ProspectionPistesRoute
  '/prospection/port-gentil': typeof ProspectionPortGentilRoute
  '/prospection/portefeuille': typeof ProspectionPortefeuilleRoute
  '/prospection/prospects': typeof ProspectionProspectsRouteWithChildren
  '/prospection/strategiques': typeof ProspectionStrategiquesRoute
  '/prospection/': typeof ProspectionIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRouteWithChildren
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/letters/$id': typeof AppLettersIdRoute
  '/_app/letters/new': typeof AppLettersNewRoute
  '/_app/lettre/$id': typeof AppLettreIdRoute
  '/_app/lettre/new': typeof AppLettreNewRoute
  '/_app/lettre/publipostage': typeof AppLettrePublipostageRoute
  '/_app/quotations/$id': typeof AppQuotationsIdRouteWithChildren
  '/_app/quotations/new': typeof AppQuotationsNewRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/staff/sync': typeof ApiStaffSyncRoute
  '/prospection/clients/$id': typeof ProspectionClientsIdRoute
  '/prospection/prospects/$id': typeof ProspectionProspectsIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/letters/': typeof AppLettersIndexRoute
  '/_app/lettre/': typeof AppLettreIndexRoute
  '/_app/quotations/': typeof AppQuotationsIndexRoute
  '/prospection/clients/': typeof ProspectionClientsIndexRoute
  '/prospection/prospects/': typeof ProspectionProspectsIndexRoute
  '/_app/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/_app/quotations/$id/edit': typeof AppQuotationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compte-supprime'
    | '/equipe'
    | '/hub'
    | '/login'
    | '/onboarding'
    | '/prospection'
    | '/quotas'
    | '/signup'
    | '/sitemap.xml'
    | '/archive'
    | '/bilan'
    | '/dashboard'
    | '/documentation'
    | '/documents'
    | '/home'
    | '/invoices'
    | '/lettre'
    | '/mails'
    | '/notifications'
    | '/poles'
    | '/profile'
    | '/quotations'
    | '/search'
    | '/services'
    | '/settings'
    | '/templates'
    | '/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/prospection/actions'
    | '/prospection/activites'
    | '/prospection/admin'
    | '/prospection/agenda'
    | '/prospection/bibliotheque'
    | '/prospection/budget'
    | '/prospection/clients'
    | '/prospection/equipe'
    | '/prospection/import'
    | '/prospection/kpi'
    | '/prospection/notifications'
    | '/prospection/objectifs'
    | '/prospection/opportunites'
    | '/prospection/pipeline'
    | '/prospection/piste'
    | '/prospection/pistes'
    | '/prospection/port-gentil'
    | '/prospection/portefeuille'
    | '/prospection/prospects'
    | '/prospection/strategiques'
    | '/prospection/'
    | '/clients/$id'
    | '/clients/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/letters/$id'
    | '/letters/new'
    | '/lettre/$id'
    | '/lettre/new'
    | '/lettre/publipostage'
    | '/quotations/$id'
    | '/quotations/new'
    | '/api/cron/billing'
    | '/api/staff/sync'
    | '/prospection/clients/$id'
    | '/prospection/prospects/$id'
    | '/clients/'
    | '/invoices/'
    | '/letters/'
    | '/lettre/'
    | '/quotations/'
    | '/prospection/clients/'
    | '/prospection/prospects/'
    | '/invoices/$id/edit'
    | '/quotations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compte-supprime'
    | '/equipe'
    | '/hub'
    | '/login'
    | '/onboarding'
    | '/quotas'
    | '/signup'
    | '/sitemap.xml'
    | '/archive'
    | '/bilan'
    | '/dashboard'
    | '/documentation'
    | '/documents'
    | '/home'
    | '/mails'
    | '/notifications'
    | '/poles'
    | '/profile'
    | '/search'
    | '/services'
    | '/settings'
    | '/templates'
    | '/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/prospection/actions'
    | '/prospection/activites'
    | '/prospection/admin'
    | '/prospection/agenda'
    | '/prospection/bibliotheque'
    | '/prospection/budget'
    | '/prospection/equipe'
    | '/prospection/import'
    | '/prospection/kpi'
    | '/prospection/notifications'
    | '/prospection/objectifs'
    | '/prospection/opportunites'
    | '/prospection/pipeline'
    | '/prospection/piste'
    | '/prospection/pistes'
    | '/prospection/port-gentil'
    | '/prospection/portefeuille'
    | '/prospection/strategiques'
    | '/prospection'
    | '/clients/$id'
    | '/clients/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/letters/$id'
    | '/letters/new'
    | '/lettre/$id'
    | '/lettre/new'
    | '/lettre/publipostage'
    | '/quotations/$id'
    | '/quotations/new'
    | '/api/cron/billing'
    | '/api/staff/sync'
    | '/prospection/clients/$id'
    | '/prospection/prospects/$id'
    | '/clients'
    | '/invoices'
    | '/letters'
    | '/lettre'
    | '/quotations'
    | '/prospection/clients'
    | '/prospection/prospects'
    | '/invoices/$id/edit'
    | '/quotations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/compte-supprime'
    | '/equipe'
    | '/hub'
    | '/login'
    | '/onboarding'
    | '/prospection'
    | '/quotas'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/archive'
    | '/_app/bilan'
    | '/_app/dashboard'
    | '/_app/documentation'
    | '/_app/documents'
    | '/_app/home'
    | '/_app/invoices'
    | '/_app/lettre'
    | '/_app/mails'
    | '/_app/notifications'
    | '/_app/poles'
    | '/_app/profile'
    | '/_app/quotations'
    | '/_app/search'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/prospection/actions'
    | '/prospection/activites'
    | '/prospection/admin'
    | '/prospection/agenda'
    | '/prospection/bibliotheque'
    | '/prospection/budget'
    | '/prospection/clients'
    | '/prospection/equipe'
    | '/prospection/import'
    | '/prospection/kpi'
    | '/prospection/notifications'
    | '/prospection/objectifs'
    | '/prospection/opportunites'
    | '/prospection/pipeline'
    | '/prospection/piste'
    | '/prospection/pistes'
    | '/prospection/port-gentil'
    | '/prospection/portefeuille'
    | '/prospection/prospects'
    | '/prospection/strategiques'
    | '/prospection/'
    | '/_app/clients/$id'
    | '/_app/clients/new'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/_app/letters/$id'
    | '/_app/letters/new'
    | '/_app/lettre/$id'
    | '/_app/lettre/new'
    | '/_app/lettre/publipostage'
    | '/_app/quotations/$id'
    | '/_app/quotations/new'
    | '/api/cron/billing'
    | '/api/staff/sync'
    | '/prospection/clients/$id'
    | '/prospection/prospects/$id'
    | '/_app/clients/'
    | '/_app/invoices/'
    | '/_app/letters/'
    | '/_app/lettre/'
    | '/_app/quotations/'
    | '/prospection/clients/'
    | '/prospection/prospects/'
    | '/_app/invoices/$id/edit'
    | '/_app/quotations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompteSupprimeRoute: typeof CompteSupprimeRoute
  EquipeRoute: typeof EquipeRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProspectionRoute: typeof ProspectionRouteWithChildren
  QuotasRoute: typeof QuotasRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  ApiCronBillingRoute: typeof ApiCronBillingRoute
  ApiStaffSyncRoute: typeof ApiStaffSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte-supprime': {
      id: '/compte-supprime'
      path: '/compte-supprime'
      fullPath: '/compte-supprime'
      preLoaderRoute: typeof CompteSupprimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotas': {
      id: '/quotas'
      path: '/quotas'
      fullPath: '/quotas'
      preLoaderRoute: typeof QuotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bilan': {
      id: '/_app/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof AppBilanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lettre': {
      id: '/_app/lettre'
      path: '/lettre'
      fullPath: '/lettre'
      preLoaderRoute: typeof AppLettreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mails': {
      id: '/_app/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof AppMailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/poles': {
      id: '/_app/poles'
      path: '/poles'
      fullPath: '/poles'
      preLoaderRoute: typeof AppPolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection/': {
      id: '/prospection/'
      path: '/'
      fullPath: '/prospection/'
      preLoaderRoute: typeof ProspectionIndexRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/actions': {
      id: '/prospection/actions'
      path: '/actions'
      fullPath: '/prospection/actions'
      preLoaderRoute: typeof ProspectionActionsRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/activites': {
      id: '/prospection/activites'
      path: '/activites'
      fullPath: '/prospection/activites'
      preLoaderRoute: typeof ProspectionActivitesRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/admin': {
      id: '/prospection/admin'
      path: '/admin'
      fullPath: '/prospection/admin'
      preLoaderRoute: typeof ProspectionAdminRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/agenda': {
      id: '/prospection/agenda'
      path: '/agenda'
      fullPath: '/prospection/agenda'
      preLoaderRoute: typeof ProspectionAgendaRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/bibliotheque': {
      id: '/prospection/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/prospection/bibliotheque'
      preLoaderRoute: typeof ProspectionBibliothequeRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/budget': {
      id: '/prospection/budget'
      path: '/budget'
      fullPath: '/prospection/budget'
      preLoaderRoute: typeof ProspectionBudgetRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/clients': {
      id: '/prospection/clients'
      path: '/clients'
      fullPath: '/prospection/clients'
      preLoaderRoute: typeof ProspectionClientsRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/equipe': {
      id: '/prospection/equipe'
      path: '/equipe'
      fullPath: '/prospection/equipe'
      preLoaderRoute: typeof ProspectionEquipeRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/import': {
      id: '/prospection/import'
      path: '/import'
      fullPath: '/prospection/import'
      preLoaderRoute: typeof ProspectionImportRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/kpi': {
      id: '/prospection/kpi'
      path: '/kpi'
      fullPath: '/prospection/kpi'
      preLoaderRoute: typeof ProspectionKpiRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/notifications': {
      id: '/prospection/notifications'
      path: '/notifications'
      fullPath: '/prospection/notifications'
      preLoaderRoute: typeof ProspectionNotificationsRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/objectifs': {
      id: '/prospection/objectifs'
      path: '/objectifs'
      fullPath: '/prospection/objectifs'
      preLoaderRoute: typeof ProspectionObjectifsRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/opportunites': {
      id: '/prospection/opportunites'
      path: '/opportunites'
      fullPath: '/prospection/opportunites'
      preLoaderRoute: typeof ProspectionOpportunitesRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/pipeline': {
      id: '/prospection/pipeline'
      path: '/pipeline'
      fullPath: '/prospection/pipeline'
      preLoaderRoute: typeof ProspectionPipelineRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/piste': {
      id: '/prospection/piste'
      path: '/piste'
      fullPath: '/prospection/piste'
      preLoaderRoute: typeof ProspectionPisteRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/pistes': {
      id: '/prospection/pistes'
      path: '/pistes'
      fullPath: '/prospection/pistes'
      preLoaderRoute: typeof ProspectionPistesRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/port-gentil': {
      id: '/prospection/port-gentil'
      path: '/port-gentil'
      fullPath: '/prospection/port-gentil'
      preLoaderRoute: typeof ProspectionPortGentilRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/portefeuille': {
      id: '/prospection/portefeuille'
      path: '/portefeuille'
      fullPath: '/prospection/portefeuille'
      preLoaderRoute: typeof ProspectionPortefeuilleRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/prospects': {
      id: '/prospection/prospects'
      path: '/prospects'
      fullPath: '/prospection/prospects'
      preLoaderRoute: typeof ProspectionProspectsRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/prospection/strategiques': {
      id: '/prospection/strategiques'
      path: '/strategiques'
      fullPath: '/prospection/strategiques'
      preLoaderRoute: typeof ProspectionStrategiquesRouteImport
      parentRoute: typeof ProspectionRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/letters/': {
      id: '/_app/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof AppLettersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/letters/$id': {
      id: '/_app/letters/$id'
      path: '/letters/$id'
      fullPath: '/letters/$id'
      preLoaderRoute: typeof AppLettersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/letters/new': {
      id: '/_app/letters/new'
      path: '/letters/new'
      fullPath: '/letters/new'
      preLoaderRoute: typeof AppLettersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lettre/': {
      id: '/_app/lettre/'
      path: '/'
      fullPath: '/lettre/'
      preLoaderRoute: typeof AppLettreIndexRouteImport
      parentRoute: typeof AppLettreRoute
    }
    '/_app/lettre/$id': {
      id: '/_app/lettre/$id'
      path: '/$id'
      fullPath: '/lettre/$id'
      preLoaderRoute: typeof AppLettreIdRouteImport
      parentRoute: typeof AppLettreRoute
    }
    '/_app/lettre/new': {
      id: '/_app/lettre/new'
      path: '/new'
      fullPath: '/lettre/new'
      preLoaderRoute: typeof AppLettreNewRouteImport
      parentRoute: typeof AppLettreRoute
    }
    '/_app/lettre/publipostage': {
      id: '/_app/lettre/publipostage'
      path: '/publipostage'
      fullPath: '/lettre/publipostage'
      preLoaderRoute: typeof AppLettrePublipostageRouteImport
      parentRoute: typeof AppLettreRoute
    }
    '/_app/quotations/': {
      id: '/_app/quotations/'
      path: '/'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
    '/_app/quotations/$id': {
      id: '/_app/quotations/$id'
      path: '/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AppQuotationsIdRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
    '/_app/quotations/new': {
      id: '/_app/quotations/new'
      path: '/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AppQuotationsNewRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
    '/api/cron/billing': {
      id: '/api/cron/billing'
      path: '/api/cron/billing'
      fullPath: '/api/cron/billing'
      preLoaderRoute: typeof ApiCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/sync': {
      id: '/api/staff/sync'
      path: '/api/staff/sync'
      fullPath: '/api/staff/sync'
      preLoaderRoute: typeof ApiStaffSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection/clients/': {
      id: '/prospection/clients/'
      path: '/'
      fullPath: '/prospection/clients/'
      preLoaderRoute: typeof ProspectionClientsIndexRouteImport
      parentRoute: typeof ProspectionClientsRoute
    }
    '/prospection/clients/$id': {
      id: '/prospection/clients/$id'
      path: '/$id'
      fullPath: '/prospection/clients/$id'
      preLoaderRoute: typeof ProspectionClientsIdRouteImport
      parentRoute: typeof ProspectionClientsRoute
    }
    '/prospection/prospects/': {
      id: '/prospection/prospects/'
      path: '/'
      fullPath: '/prospection/prospects/'
      preLoaderRoute: typeof ProspectionProspectsIndexRouteImport
      parentRoute: typeof ProspectionProspectsRoute
    }
    '/prospection/prospects/$id': {
      id: '/prospection/prospects/$id'
      path: '/$id'
      fullPath: '/prospection/prospects/$id'
      preLoaderRoute: typeof ProspectionProspectsIdRouteImport
      parentRoute: typeof ProspectionProspectsRoute
    }
    '/_app/invoices/$id/edit': {
      id: '/_app/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AppInvoicesIdEditRouteImport
      parentRoute: typeof AppInvoicesIdRoute
    }
    '/_app/quotations/$id/edit': {
      id: '/_app/quotations/$id/edit'
      path: '/edit'
      fullPath: '/quotations/$id/edit'
      preLoaderRoute: typeof AppQuotationsIdEditRouteImport
      parentRoute: typeof AppQuotationsIdRoute
    }
  }
}

interface AppInvoicesIdRouteChildren {
  AppInvoicesIdEditRoute: typeof AppInvoicesIdEditRoute
}

const AppInvoicesIdRouteChildren: AppInvoicesIdRouteChildren = {
  AppInvoicesIdEditRoute: AppInvoicesIdEditRoute,
}

const AppInvoicesIdRouteWithChildren = AppInvoicesIdRoute._addFileChildren(
  AppInvoicesIdRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRouteWithChildren
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRouteWithChildren,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppLettreRouteChildren {
  AppLettreIdRoute: typeof AppLettreIdRoute
  AppLettreNewRoute: typeof AppLettreNewRoute
  AppLettrePublipostageRoute: typeof AppLettrePublipostageRoute
  AppLettreIndexRoute: typeof AppLettreIndexRoute
}

const AppLettreRouteChildren: AppLettreRouteChildren = {
  AppLettreIdRoute: AppLettreIdRoute,
  AppLettreNewRoute: AppLettreNewRoute,
  AppLettrePublipostageRoute: AppLettrePublipostageRoute,
  AppLettreIndexRoute: AppLettreIndexRoute,
}

const AppLettreRouteWithChildren = AppLettreRoute._addFileChildren(
  AppLettreRouteChildren,
)

interface AppQuotationsIdRouteChildren {
  AppQuotationsIdEditRoute: typeof AppQuotationsIdEditRoute
}

const AppQuotationsIdRouteChildren: AppQuotationsIdRouteChildren = {
  AppQuotationsIdEditRoute: AppQuotationsIdEditRoute,
}

const AppQuotationsIdRouteWithChildren = AppQuotationsIdRoute._addFileChildren(
  AppQuotationsIdRouteChildren,
)

interface AppQuotationsRouteChildren {
  AppQuotationsIdRoute: typeof AppQuotationsIdRouteWithChildren
  AppQuotationsNewRoute: typeof AppQuotationsNewRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
}

const AppQuotationsRouteChildren: AppQuotationsRouteChildren = {
  AppQuotationsIdRoute: AppQuotationsIdRouteWithChildren,
  AppQuotationsNewRoute: AppQuotationsNewRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
}

const AppQuotationsRouteWithChildren = AppQuotationsRoute._addFileChildren(
  AppQuotationsRouteChildren,
)

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppBilanRoute: typeof AppBilanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppLettreRoute: typeof AppLettreRouteWithChildren
  AppMailsRoute: typeof AppMailsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPolesRoute: typeof AppPolesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuotationsRoute: typeof AppQuotationsRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppLettersIdRoute: typeof AppLettersIdRoute
  AppLettersNewRoute: typeof AppLettersNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppLettersIndexRoute: typeof AppLettersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppBilanRoute: AppBilanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppLettreRoute: AppLettreRouteWithChildren,
  AppMailsRoute: AppMailsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPolesRoute: AppPolesRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuotationsRoute: AppQuotationsRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUsersRoute: AppUsersRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppLettersIdRoute: AppLettersIdRoute,
  AppLettersNewRoute: AppLettersNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppLettersIndexRoute: AppLettersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProspectionClientsRouteChildren {
  ProspectionClientsIdRoute: typeof ProspectionClientsIdRoute
  ProspectionClientsIndexRoute: typeof ProspectionClientsIndexRoute
}

const ProspectionClientsRouteChildren: ProspectionClientsRouteChildren = {
  ProspectionClientsIdRoute: ProspectionClientsIdRoute,
  ProspectionClientsIndexRoute: ProspectionClientsIndexRoute,
}

const ProspectionClientsRouteWithChildren =
  ProspectionClientsRoute._addFileChildren(ProspectionClientsRouteChildren)

interface ProspectionProspectsRouteChildren {
  ProspectionProspectsIdRoute: typeof ProspectionProspectsIdRoute
  ProspectionProspectsIndexRoute: typeof ProspectionProspectsIndexRoute
}

const ProspectionProspectsRouteChildren: ProspectionProspectsRouteChildren = {
  ProspectionProspectsIdRoute: ProspectionProspectsIdRoute,
  ProspectionProspectsIndexRoute: ProspectionProspectsIndexRoute,
}

const ProspectionProspectsRouteWithChildren =
  ProspectionProspectsRoute._addFileChildren(ProspectionProspectsRouteChildren)

interface ProspectionRouteChildren {
  ProspectionActionsRoute: typeof ProspectionActionsRoute
  ProspectionActivitesRoute: typeof ProspectionActivitesRoute
  ProspectionAdminRoute: typeof ProspectionAdminRoute
  ProspectionAgendaRoute: typeof ProspectionAgendaRoute
  ProspectionBibliothequeRoute: typeof ProspectionBibliothequeRoute
  ProspectionBudgetRoute: typeof ProspectionBudgetRoute
  ProspectionClientsRoute: typeof ProspectionClientsRouteWithChildren
  ProspectionEquipeRoute: typeof ProspectionEquipeRoute
  ProspectionImportRoute: typeof ProspectionImportRoute
  ProspectionKpiRoute: typeof ProspectionKpiRoute
  ProspectionNotificationsRoute: typeof ProspectionNotificationsRoute
  ProspectionObjectifsRoute: typeof ProspectionObjectifsRoute
  ProspectionOpportunitesRoute: typeof ProspectionOpportunitesRoute
  ProspectionPipelineRoute: typeof ProspectionPipelineRoute
  ProspectionPisteRoute: typeof ProspectionPisteRoute
  ProspectionPistesRoute: typeof ProspectionPistesRoute
  ProspectionPortGentilRoute: typeof ProspectionPortGentilRoute
  ProspectionPortefeuilleRoute: typeof ProspectionPortefeuilleRoute
  ProspectionProspectsRoute: typeof ProspectionProspectsRouteWithChildren
  ProspectionStrategiquesRoute: typeof ProspectionStrategiquesRoute
  ProspectionIndexRoute: typeof ProspectionIndexRoute
}

const ProspectionRouteChildren: ProspectionRouteChildren = {
  ProspectionActionsRoute: ProspectionActionsRoute,
  ProspectionActivitesRoute: ProspectionActivitesRoute,
  ProspectionAdminRoute: ProspectionAdminRoute,
  ProspectionAgendaRoute: ProspectionAgendaRoute,
  ProspectionBibliothequeRoute: ProspectionBibliothequeRoute,
  ProspectionBudgetRoute: ProspectionBudgetRoute,
  ProspectionClientsRoute: ProspectionClientsRouteWithChildren,
  ProspectionEquipeRoute: ProspectionEquipeRoute,
  ProspectionImportRoute: ProspectionImportRoute,
  ProspectionKpiRoute: ProspectionKpiRoute,
  ProspectionNotificationsRoute: ProspectionNotificationsRoute,
  ProspectionObjectifsRoute: ProspectionObjectifsRoute,
  ProspectionOpportunitesRoute: ProspectionOpportunitesRoute,
  ProspectionPipelineRoute: ProspectionPipelineRoute,
  ProspectionPisteRoute: ProspectionPisteRoute,
  ProspectionPistesRoute: ProspectionPistesRoute,
  ProspectionPortGentilRoute: ProspectionPortGentilRoute,
  ProspectionPortefeuilleRoute: ProspectionPortefeuilleRoute,
  ProspectionProspectsRoute: ProspectionProspectsRouteWithChildren,
  ProspectionStrategiquesRoute: ProspectionStrategiquesRoute,
  ProspectionIndexRoute: ProspectionIndexRoute,
}

const ProspectionRouteWithChildren = ProspectionRoute._addFileChildren(
  ProspectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompteSupprimeRoute: CompteSupprimeRoute,
  EquipeRoute: EquipeRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProspectionRoute: ProspectionRouteWithChildren,
  QuotasRoute: QuotasRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  ApiCronBillingRoute: ApiCronBillingRoute,
  ApiStaffSyncRoute: ApiStaffSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
